### PR TITLE
[#20] Drop leading slashes in 2nd gen paths

### PR DESCRIPTION
**Pull request by hiddenalpha**
Drop leading slashes in paths using filter utility during java code
generation.

### CODE REVIEW

**Comment by nidi3** [comment]
Please follow the style of the existing code. 

- requires variable with lowercase
- no use strict
- no Object.create

**Comment by hiddenalpha** [comment]
Applied requested changes (2nd run). Originating in [comment posted on issue](https://github.com/swisspush/apikana/issues/20#issuecomment-390913574).

Decision for our project was to solve this in apikana rather fixing our services because that would take lot more time to achieve.

**Comment by hiddenalpha** [comment]
See also adaption of apikana-java in swisspush/apikana-java#9.

**Comment by hiddenalpha** [comment]
Ready to review :) (@nidi3, @lbovet)

**Pull request merged**
