### PR TITLE
Fix gitignore for template files in templates folder

### PR DESCRIPTION
**Pull request by naamor**

### CODE REVIEW

**Comment by lbovet** [comment]
What is the effect of the proposed change?
You exclude templates/ from ignores. But it should already be the case, no? Everything that is not ignored is taken by default.

**Comment by naamor** [comment]
Because of the "gen" in generated gitignore and the "gen" in template path "root_directory/templates/plugin_name/gen/plugin_name/filename.ext" the template files are ignored too.

**Comment by lbovet** [comment]
Oh, I see now. We could also have "/gen/" in .gitignore to ignore it only if it is on the root. Probably better.

**Comment by naamor** [comment]
Thanks for your feedback. I like your solution. Made a new commit

**Comment by lbovet** [comment]
Thx!

**Pull request merged**
